### ISSUE TITLE
stats

### ISSUE THREAD

**Issue by deeepgandhi** [rosenfeldamir/incremental_learning#1]
could you also upload the decathlon stats file?

**Comment by rosenfeldamir** [comment]
Uploaded as a pickle file (python 3).

**Comment by deeepgandhi** [comment]
so sorry to bother you again but which file is database_stats_extra? It
would be hepful if you could share your decathlon file, the whole thing!
thanking you,
deep



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/12/19,
5:04:21 AM

**Comment by rosenfeldamir** [comment]
Come to think of it, there are now works that include this one as a special case. Specifically, see [here](https://github.com/srebuffi/residual_adapters) ; I've also updated this in the README. I recommend
 using their repo as it's well written and self contained :-) . It contains also the implementation of " "Learning multiple visual domains with residual adapters", which came after this work but is practically equivalent in terms of the method.
